### ISSUE TITLE
Delivery time for combinations

### ISSUE THREAD

**Issue by futurowebpl** [saleslayer/Sales_Layer_Prestashop#1]
What should be done on the connector side  to allow the flow of information from the module: 

https://addons.prestashop.com/pl/deklinacje-personalizacja-produktow/40376-delivery-time-for-combinations.html#overview

**Comment by Jan-SL** [comment]
Hello, first of all follow the manual how to customize the plugin put the variable i am developer to true. Just put the field name that you want to use in the saleslayerimport.php file in the definition of fields in public $ product_format_base_fields
         = array ('allfields fields', 'my new_field', ...); So your field doesn't become a variant attribute. Then you can add your code that you need that the plugin does in the SlVariants.php file. Look for a comment that says: "Place your custom non multi-language code here". You can add a query to the database if you add if (isset ($ product_format ['data'] ['my new field']) {
// your code
}.
If you need, talk to our customer success but in the manual you will find what you must do to customize the plugin. Keep in mind that we cannot adjust our plugin to all the prestashop plugins but it can be edited more or less easily so that it does what you need.
